#!/usr/bin/env php

<?php
/**
 * Magma Sf project deployment console command app
 * @author Romain BRUCKERT
 * Github {@link https://github.com/adadgio/magma}
 */
define('MAGMA_VERSION', '1.0');
set_time_limit(0);
date_default_timezone_set('Europe/Paris');

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use Symfony\Component\Console\Application;

$app = new Application('Magma Sf project deployment tool', MAGMA_VERSION);
$app->add(new Magma\Command\ConfigTestCommand());

$app->add(new Magma\Command\ReleaseSetupCommand());
$app->add(new Magma\Command\ReleaseUploadCommand());
$app->add(new Magma\Command\ReleaseShareCommand());

$app->add(new Magma\Command\ReleasePreDeployCommand());
$app->add(new Magma\Command\CachePermissionsCommand());
$app->add(new Magma\Command\ReleasePublishCommand()); // the website actually goes live!
$app->add(new Magma\Command\ReleasePostDeployCommand());

// can execute all the above commands in order
$app->add(new Magma\Command\DeployCommand());
$app->run();
